"""cascade resolve request on users delete

Revision ID: 495872fa91e6
Revises: aa12b98ce3d1
Create Date: 2026-04-25 11:04:40.415371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495872fa91e6'
down_revision: Union[str, Sequence[str], None] = 'aa12b98ce3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_resolve_requests_external_request_id_key'), 'user_resolve_requests', type_='unique')
    op.drop_constraint(op.f('user_resolve_requests_user_id_fkey'), 'user_resolve_requests', type_='foreignkey')
    op.create_foreign_key(None, 'user_resolve_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_resolve_requests', type_='foreignkey')
    op.create_foreign_key(op.f('user_resolve_requests_user_id_fkey'), 'user_resolve_requests', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('user_resolve_requests_external_request_id_key'), 'user_resolve_requests', ['external_request_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
